# Generated by Django 5.2 on 2025-04-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_category_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news365',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='news365',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
